codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 13

coverage:
  precision: 2
  round: down
  range: "70...85"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  after_n_builds: 13
