target = "https://www.rfc-editor.org/rfc/rfc9103#section-6.2"

# Update to RFC 5936 for AXFR over TCP
#
#    For clarity, an AXFR-over-TCP server compliant with this
#    specification MUST be able to handle multiple concurrent AXoT
#    sessions on a single TCP connection (for the same and different
#    zones).  The response streams for concurrent AXFRs MAY be
#    intermingled, and AXFR-over-TCP clients compliant with this
#    specification, which pipeline AXFR requests, MUST be able to handle
#    this.

[[spec]]
level = "MUST"
quote = '''
For clarity, an AXFR-over-TCP server compliant with this
specification MUST be able to handle multiple concurrent AXoT
sessions on a single TCP connection (for the same and different
zones).
'''

[[spec]]
level = "MUST"
quote = '''
The response streams for concurrent AXFRs MAY be
intermingled, and AXFR-over-TCP clients compliant with this
specification, which pipeline AXFR requests, MUST be able to handle
this.
'''

