target = "https://www.rfc-editor.org/rfc/rfc6762#section-18.4"

# AA (Authoritative Answer) Bit
#
#    In query messages, the Authoritative Answer bit MUST be zero on
#    transmission, and MUST be ignored on reception.
# 
#    In response messages for Multicast domains, the Authoritative Answer
#    bit MUST be set to one (not setting this bit would imply there's some
#    other place where "better" information may be found) and MUST be
#    ignored on reception.

[[spec]]
level = "MUST"
quote = '''
In query messages, the Authoritative Answer bit MUST be zero on
transmission, and MUST be ignored on reception.
'''

[[spec]]
level = "MUST"
quote = '''
In response messages for Multicast domains, the Authoritative Answer
bit MUST be set to one (not setting this bit would imply there's some
other place where "better" information may be found) and MUST be
ignored on reception.
'''

