target = "https://www.rfc-editor.org/rfc/rfc6762#section-22.1"

# Domain Name Reservation Considerations
#
#    The six domains listed above, and any names falling within those
#    domains (e.g., "MyPrinter.local.", "34.12.254.169.in-addr.arpa.",
#    "Ink-Jet._pdl-datastream._tcp.local.") are special [RFC6761] in the
#    following ways:
# 
#       1. Users may use these names as they would other DNS names,
#          entering them anywhere that they would otherwise enter a
#          conventional DNS name, or a dotted decimal IPv4 address, or a
#          literal IPv6 address.
# 
#          Since there is no central authority responsible for assigning
#          dot-local names, and all devices on the local network are
#          equally entitled to claim any dot-local name, users SHOULD be
# 
#          aware of this and SHOULD exercise appropriate caution.  In an
#          untrusted or unfamiliar network environment, users SHOULD be
#          aware that using a name like "www.local" may not actually
#          connect them to the web site they expected, and could easily
#          connect them to a different web page, or even a fake or spoof
#          of their intended web site, designed to trick them into
#          revealing confidential information.  As always with networking,
#          end-to-end cryptographic security can be a useful tool.  For
#          example, when connecting with ssh, the ssh host key
#          verification process will inform the user if it detects that
#          the identity of the entity they are communicating with has
#          changed since the last time they connected to that name.
# 
#       2. Application software may use these names as they would other
#          similar DNS names, and is not required to recognize the names
#          and treat them specially.  Due to the relative ease of spoofing
#          dot-local names, end-to-end cryptographic security remains
#          important when communicating across a local network, just as it
#          is when communicating across the global Internet.
# 
#       3. Name resolution APIs and libraries SHOULD recognize these names
#          as special and SHOULD NOT send queries for these names to their
#          configured (unicast) caching DNS server(s).  This is to avoid
#          unnecessary load on the root name servers and other name
#          servers, caused by queries for which those name servers do not
#          have useful non-negative answers to give, and will not ever
#          have useful non-negative answers to give.
# 
#       4. Caching DNS servers SHOULD recognize these names as special and
#          SHOULD NOT attempt to look up NS records for them, or otherwise
#          query authoritative DNS servers in an attempt to resolve these
#          names.  Instead, caching DNS servers SHOULD generate immediate
#          NXDOMAIN responses for all such queries they may receive (from
#          misbehaving name resolver libraries).  This is to avoid
#          unnecessary load on the root name servers and other name
#          servers.
# 
#       5. Authoritative DNS servers SHOULD NOT by default be configurable
#          to answer queries for these names, and, like caching DNS
#          servers, SHOULD generate immediate NXDOMAIN responses for all
#          such queries they may receive.  DNS server software MAY provide
#          a configuration option to override this default, for testing
#          purposes or other specialized uses.
# 
#       6. DNS server operators SHOULD NOT attempt to configure
#          authoritative DNS servers to act as authoritative for any of
#          these names.  Configuring an authoritative DNS server to act as
#          authoritative for any of these names may not, in many cases,
# 
#          yield the expected result.  Since name resolver libraries and
#          caching DNS servers SHOULD NOT send queries for those names
#          (see 3 and 4 above), such queries SHOULD be suppressed before
#          they even reach the authoritative DNS server in question, and
#          consequently it will not even get an opportunity to answer
#          them.
# 
#       7. DNS Registrars MUST NOT allow any of these names to be
#          registered in the normal way to any person or entity.  These
#          names are reserved protocol identifiers with special meaning
#          and fall outside the set of names available for allocation by
#          registrars.  Attempting to allocate one of these names as if it
#          were a normal domain name will probably not work as desired,
#          for reasons 3, 4, and 6 above.

[[spec]]
level = "SHOULD"
quote = '''
Since there is no central authority responsible for assigning
dot-local names, and all devices on the local network are
equally entitled to claim any dot-local name, users SHOULD be
'''

[[spec]]
level = "SHOULD"
quote = '''
aware of this and SHOULD exercise appropriate caution.
'''

[[spec]]
level = "SHOULD"
quote = '''
In an
untrusted or unfamiliar network environment, users SHOULD be
aware that using a name like "www.local" may not actually
connect them to the web site they expected, and could easily
connect them to a different web page, or even a fake or spoof
of their intended web site, designed to trick them into
revealing confidential information.
'''

[[spec]]
level = "SHOULD"
quote = '''
Name resolution APIs and libraries SHOULD recognize these names
as special and SHOULD NOT send queries for these names to their
configured (unicast) caching DNS server(s).
'''

[[spec]]
level = "SHOULD"
quote = '''
Caching DNS servers SHOULD recognize these names as special and
SHOULD NOT attempt to look up NS records for them, or otherwise
query authoritative DNS servers in an attempt to resolve these
names.
'''

[[spec]]
level = "SHOULD"
quote = '''
Instead, caching DNS servers SHOULD generate immediate
NXDOMAIN responses for all such queries they may receive (from
misbehaving name resolver libraries).
'''

[[spec]]
level = "SHOULD"
quote = '''
Authoritative DNS servers SHOULD NOT by default be configurable
to answer queries for these names, and, like caching DNS
servers, SHOULD generate immediate NXDOMAIN responses for all
such queries they may receive.
'''

[[spec]]
level = "MAY"
quote = '''
DNS server software MAY provide
a configuration option to override this default, for testing
purposes or other specialized uses.
'''

[[spec]]
level = "SHOULD"
quote = '''
DNS server operators SHOULD NOT attempt to configure
authoritative DNS servers to act as authoritative for any of
these names.
'''

[[spec]]
level = "SHOULD"
quote = '''
Since name resolver libraries and
caching DNS servers SHOULD NOT send queries for those names
(see 3 and 4 above), such queries SHOULD be suppressed before
they even reach the authoritative DNS server in question, and
consequently it will not even get an opportunity to answer
them.
'''

[[spec]]
level = "MUST"
quote = '''
DNS Registrars MUST NOT allow any of these names to be
registered in the normal way to any person or entity.
'''

