target = "https://www.rfc-editor.org/rfc/rfc8945#section-5.2.4"

# Truncation Check and Error Handling
#
#    If a TSIG is received with truncation that is permitted per
#    Section 5.2.2.1 but the MAC is too short for the local policy in
#    force, an RCODE 9 (NOTAUTH) and TSIG ERROR 22 (BADTRUNC) MUST be
#    returned.  The server SHOULD log the error.

[[spec]]
level = "MUST"
quote = '''
If a TSIG is received with truncation that is permitted per
Section 5.2.2.1 but the MAC is too short for the local policy in
force, an RCODE 9 (NOTAUTH) and TSIG ERROR 22 (BADTRUNC) MUST be
returned.
'''

[[spec]]
level = "SHOULD"
quote = '''
The server SHOULD log the error.
'''

