target = "https://www.rfc-editor.org/rfc/rfc4034#section-2.1.1"

# The Flags Field
#
#    Bit 7 of the Flags field is the Zone Key flag.  If bit 7 has value 1,
#    then the DNSKEY record holds a DNS zone key, and the DNSKEY RR's
#    owner name MUST be the name of a zone.  If bit 7 has value 0, then
#    the DNSKEY record holds some other type of DNS public key and MUST
#    NOT be used to verify RRSIGs that cover RRsets.
# 
#    Bit 15 of the Flags field is the Secure Entry Point flag, described
#    in [RFC3757].  If bit 15 has value 1, then the DNSKEY record holds a
#    key intended for use as a secure entry point.  This flag is only
# 
#    intended to be a hint to zone signing or debugging software as to the
#    intended use of this DNSKEY record; validators MUST NOT alter their
#    behavior during the signature validation process in any way based on
#    the setting of this bit.  This also means that a DNSKEY RR with the
#    SEP bit set would also need the Zone Key flag set in order to be able
#    to generate signatures legally.  A DNSKEY RR with the SEP set and the
#    Zone Key flag not set MUST NOT be used to verify RRSIGs that cover
#    RRsets.
# 
#    Bits 0-6 and 8-14 are reserved: these bits MUST have value 0 upon
#    creation of the DNSKEY RR and MUST be ignored upon receipt.

[[spec]]
level = "MUST"
quote = '''
If bit 7 has value 1,
then the DNSKEY record holds a DNS zone key, and the DNSKEY RR's
owner name MUST be the name of a zone.
'''

[[spec]]
level = "MUST"
quote = '''
If bit 7 has value 0, then
the DNSKEY record holds some other type of DNS public key and MUST
NOT be used to verify RRSIGs that cover RRsets.
'''

[[spec]]
level = "MUST"
quote = '''
intended to be a hint to zone signing or debugging software as to the
intended use of this DNSKEY record; validators MUST NOT alter their
behavior during the signature validation process in any way based on
the setting of this bit.
'''

[[spec]]
level = "MUST"
quote = '''
A DNSKEY RR with the SEP set and the
Zone Key flag not set MUST NOT be used to verify RRSIGs that cover
RRsets.
'''

[[spec]]
level = "MUST"
quote = '''
Bits 0-6 and 8-14 are reserved: these bits MUST have value 0 upon
creation of the DNSKEY RR and MUST be ignored upon receipt.
'''

