target = "https://www.rfc-editor.org/rfc/rfc4034#section-3.1.7"

# The Signer's Name Field
#
#    The Signer's Name field value identifies the owner name of the DNSKEY
#    RR that a validator is supposed to use to validate this signature.
#    The Signer's Name field MUST contain the name of the zone of the
#    covered RRset.  A sender MUST NOT use DNS name compression on the
#    Signer's Name field when transmitting a RRSIG RR.

[[spec]]
level = "MUST"
quote = '''
The Signer's Name field MUST contain the name of the zone of the
covered RRset.
'''

[[spec]]
level = "MUST"
quote = '''
A sender MUST NOT use DNS name compression on the
Signer's Name field when transmitting a RRSIG RR.
'''

