target = "https://www.rfc-editor.org/rfc/rfc4034#section-2.1.2"

# The Protocol Field
#
#    The Protocol Field MUST have value 3, and the DNSKEY RR MUST be
#    treated as invalid during signature verification if it is found to be
#    some value other than 3.

[[spec]]
level = "MUST"
quote = '''
The Protocol Field MUST have value 3, and the DNSKEY RR MUST be
treated as invalid during signature verification if it is found to be
some value other than 3.
'''

