[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "dns-test"
publish = false
version = "0.1.0"

[dependencies]
base64.workspace = true
hex.workspace = true
minijinja.workspace = true
rcgen.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
url.workspace = true

[lib]
doctest = false

[dev-dependencies]
ctrlc.workspace = true
pretty_assertions.workspace = true

[lints]
workspace = true
