target = "https://www.rfc-editor.org/rfc/rfc6763#section-4.3"

# Internal Handling of Names
#
#    If client software takes the <Instance>, <Service>, and <Domain>
#    portions of a Service Instance Name and internally concatenates them
#    together into a single string, then because the <Instance> portion is
#    allowed to contain any characters, including dots, appropriate
#    precautions MUST be taken to ensure that DNS label boundaries are
#    properly preserved.  Client software can do this in a variety of
#    ways, such as character escaping.
# 
#    This document RECOMMENDS that if concatenating the three portions of
#    a Service Instance Name, any dots in the <Instance> portion be
#    escaped following the customary DNS convention for text files: by
#    preceding literal dots with a backslash (so "." becomes "\.").
#    Likewise, any backslashes in the <Instance> portion should also be
#    escaped by preceding them with a backslash (so "\" becomes "\\").
# 
#    Having done this, the three components of the name may be safely
#    concatenated.  The backslash-escaping allows literal dots in the name
#    (escaped) to be distinguished from label-separator dots (not
#    escaped), and the resulting concatenated string may be safely passed
#    to standard DNS APIs like res_query(), which will interpret the
#    backslash-escaped string as intended.

[[spec]]
level = "MUST"
quote = '''
If client software takes the <Instance>, <Service>, and <Domain>
portions of a Service Instance Name and internally concatenates them
together into a single string, then because the <Instance> portion is
allowed to contain any characters, including dots, appropriate
precautions MUST be taken to ensure that DNS label boundaries are
properly preserved.
'''

