[workspace]
members = ["compatibility-tests", "conformance-tests", "dns-test", "e2e-tests", "ede-dot-com", "test-server"]
resolver = "2"

[workspace.dependencies]
# hickory
hickory-net = { version = "0.26.0", path = "../crates/net", default-features = false, features = ["tokio"] }
hickory-proto = { version = "0.26.0", path = "../crates/proto", default-features = false, features = ["std"] }
test-support.path = "../tests/test-support"

# local
dns-test.path = "dns-test"

# others
anyhow = "1.0"
async-trait = "0.1"
aws-lc-rs = { version = "1.12.3", default-features = false, features = ["prebuilt-nasm"] }
base64 = "0.22.1"
clap = { version = "4.0", features = ["derive", "std"] }
ctrlc = "3.4.2"
data-encoding = "2.9"
futures = { version = "0.3.5", default-features = false }
hex = "0.4.3"
minijinja = "2"
pretty_assertions = "1.4.0"
rcgen = "0.14"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
tempfile = "3.9.0"
time = "0.3"
tokio = { version = "1.21", features = ["macros", "net", "io-util", "rt-multi-thread"] }
url = "2.5.0"

[workspace.lints.rust]
non_snake_case = "warn"
non_upper_case_globals = "warn"
rust_2018_idioms = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(nightly)'] }
unnameable_types = "warn"
unreachable_pub = "warn"
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_qualifications = "warn"

[workspace.lints.clippy]
bool_to_int_with_if = "allow"
default_trait_access = "warn"
manual_let_else = "warn"
or_fun_call = "warn"
single_component_path_imports = "allow"
upper_case_acronyms = "allow"
use_self = "warn"
