target = "https://www.rfc-editor.org/rfc/rfc9904#section-1.3"

# Requirements Notation
#
#    The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
#    "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and
#    "OPTIONAL" in this document are to be interpreted as described in
#    BCP 14 [RFC2119] [RFC8174] when, and only when, they appear in all
#    capitals, as shown here.
# 
#    [RFC2119] considers the term SHOULD to be equivalent to RECOMMENDED,
#    and SHOULD NOT equivalent to NOT RECOMMENDED.  This document has
#    chosen to use the terms RECOMMENDED and NOT RECOMMENDED, as this more
#    clearly expresses the recommendations to implementers.

[[spec]]
level = "SHOULD"
quote = '''
[RFC2119] considers the term SHOULD to be equivalent to RECOMMENDED,
and SHOULD NOT equivalent to NOT RECOMMENDED.
'''

[[spec]]
level = "SHOULD"
quote = '''
This document has
chosen to use the terms RECOMMENDED and NOT RECOMMENDED, as this more
clearly expresses the recommendations to implementers.
'''

