target = "https://www.rfc-editor.org/rfc/rfc9558#section-5.1"

# Key Sizes
#
#    The key size of GOST R 34.10-2012 public keys conforming to this
#    specification MUST be 512 bits according to RFC 7091 [RFC7091].

[[spec]]
level = "MUST"
quote = '''
The key size of GOST R 34.10-2012 public keys conforming to this
specification MUST be 512 bits according to RFC 7091 [RFC7091].
'''

