[package]
name = "test-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
aws-lc-rs.workspace = true
base64.workspace = true
clap.workspace = true
data-encoding.workspace = true
futures.workspace = true
hickory-proto.workspace = true
hickory-net = { workspace = true, features = ["dnssec-aws-lc-rs"] }
tokio.workspace = true
time = { workspace = true, features = ["formatting", "macros", "parsing"] }
