target = "https://www.rfc-editor.org/rfc/rfc9250#section-8.4"

# DNS-over-QUIC Error Codes Registry
#
#    IANA has added a registry for "DNS-over-QUIC Error Codes" on the
#    "Domain Name System (DNS) Parameters" web page.
# 
#    The "DNS-over-QUIC Error Codes" registry governs a 62-bit space.
#    This space is split into three regions that are governed by different
#    policies:
# 
#    *  Permanent registrations for values between 0x00 and 0x3f (in
#       hexadecimal; inclusive), which are assigned using Standards Action
#       or IESG Approval as defined in Sections 4.9 and 4.10 of [RFC8126]
# 
#    *  Permanent registrations for values larger than 0x3f, which are
#       assigned using the Specification Required policy ([RFC8126])
# 
#    *  Provisional registrations for values larger than 0x3f, which
#       require Expert Review, as defined in Section 4.5 of [RFC8126].
# 
#    Provisional reservations share the range of values larger than 0x3f
#    with some permanent registrations.  This is by design to enable
#    conversion of provisional registrations into permanent registrations
#    without requiring changes in deployed systems.  (This design is
#    aligned with the principles set in Section 22 of [RFC9000].)
# 
#    Registrations in this registry MUST include the following fields:
# 
#    Value:  The assigned codepoint
# 
#    Status:  "Permanent" or "Provisional"
# 
#    Contact:  Contact details for the registrant
# 
#    In addition, permanent registrations MUST include:
# 
#    Error:  A short mnemonic for the parameter
# 
#    Specification:  A reference to a publicly available specification for
#       the value (optional for provisional registrations)
# 
#    Description:  A brief description of the error code semantics, which
#       MAY be a summary if a specification reference is provided
# 
#    Provisional registrations of codepoints are intended to allow for
#    private use and experimentation with extensions to DoQ.  However,
#    provisional registrations could be reclaimed and reassigned for other
#    purposes.  In addition to the parameters listed above, provisional
#    registrations MUST include:
# 
#    Date:  The date of last update to the registration
# 
#    A request to update the date on any provisional registration can be
#    made without review from the designated expert(s).
# 
#    The initial content of this registry is shown in Table 1 and all
#    entries share the following fields:
# 
#    Status:  Permanent
# 
#    Contact:  DPRIVE WG
# 
#    Specification:  Section 4.3
# 
#    +============+=======================+=============================+
#    | Value      | Error                 | Description                 |
#    +============+=======================+=============================+
#    | 0x0        | DOQ_NO_ERROR          | No error                    |
#    +------------+-----------------------+-----------------------------+
#    | 0x1        | DOQ_INTERNAL_ERROR    | Implementation error        |
#    +------------+-----------------------+-----------------------------+
#    | 0x2        | DOQ_PROTOCOL_ERROR    | Generic protocol violation  |
#    +------------+-----------------------+-----------------------------+
#    | 0x3        | DOQ_REQUEST_CANCELLED | Request cancelled by client |
#    +------------+-----------------------+-----------------------------+
#    | 0x4        | DOQ_EXCESSIVE_LOAD    | Closing a connection for    |
#    |            |                       | excessive load              |
#    +------------+-----------------------+-----------------------------+
#    | 0x5        | DOQ_UNSPECIFIED_ERROR | No error reason specified   |
#    +------------+-----------------------+-----------------------------+
#    | 0xd098ea5e | DOQ_ERROR_RESERVED    | Alternative error code used |
#    |            |                       | for tests                   |
#    +------------+-----------------------+-----------------------------+
# 
#             Table 1: Initial DNS-over-QUIC Error Codes Entries

[[spec]]
level = "MUST"
quote = '''
Registrations in this registry MUST include the following fields:
'''

[[spec]]
level = "MUST"
quote = '''
In addition, permanent registrations MUST include:
'''

[[spec]]
level = "MAY"
quote = '''
Description:  A brief description of the error code semantics, which
MAY be a summary if a specification reference is provided
'''

[[spec]]
level = "MUST"
quote = '''
In addition to the parameters listed above, provisional
registrations MUST include:
'''

