target = "https://www.rfc-editor.org/rfc/rfc9250#section-4.2.1"

# DNS Message IDs
#
#    When sending queries over a QUIC connection, the DNS Message ID MUST
#    be set to 0.  The stream mapping for DoQ allows for unambiguous
#    correlation of queries and responses, so the Message ID field is not
#    required.
# 
#    This has implications for proxying DoQ messages to and from other
#    transports.  For example, proxies may have to manage the fact that
#    DoQ can support a larger number of outstanding queries on a single
#    connection than, for example, DNS over TCP, because DoQ is not
#    limited by the Message ID space.  This issue already exists for DoH,
#    where a Message ID of 0 is recommended.
# 
#    When forwarding a DNS message from DoQ over another transport, a DNS
#    Message ID MUST be generated according to the rules of the protocol
#    that is in use.  When forwarding a DNS message from another transport
#    over DoQ, the Message ID MUST be set to 0.

[[spec]]
level = "MUST"
quote = '''
When sending queries over a QUIC connection, the DNS Message ID MUST
be set to 0.
'''

[[spec]]
level = "MUST"
quote = '''
When forwarding a DNS message from DoQ over another transport, a DNS
Message ID MUST be generated according to the rules of the protocol
that is in use.
'''

[[spec]]
level = "MUST"
quote = '''
When forwarding a DNS message from another transport
over DoQ, the Message ID MUST be set to 0.
'''

