target = "https://www.rfc-editor.org/rfc/rfc9250#section-5.2"

# Fallback to Other Protocols on Connection Failure
#
#    If the establishment of the DoQ connection fails, clients MAY attempt
#    to fall back to DoT and then potentially cleartext, as specified in
#    DoT [RFC7858] and "Usage Profiles for DNS over TLS and DNS over DTLS"
#    [RFC8310], depending on their usage profile.
# 
#    DNS clients SHOULD remember server IP addresses that don't support
#    DoQ.  Mobile clients might also remember the lack of DoQ support by
#    given IP addresses on a per-context basis (e.g., per network or
#    provisioning domain).
# 
#    Timeouts, connection refusals, and QUIC handshake failures are
#    indicators that a server does not support DoQ.  Clients SHOULD NOT
#    attempt DoQ queries to a server that does not support DoQ for a
#    reasonable period (such as one hour per server).  DNS clients
#    following an out-of-band key-pinned usage profile [RFC7858] MAY be
#    more aggressive about retrying after DoQ connection failures.

[[spec]]
level = "MAY"
quote = '''
If the establishment of the DoQ connection fails, clients MAY attempt
to fall back to DoT and then potentially cleartext, as specified in
DoT [RFC7858] and "Usage Profiles for DNS over TLS and DNS over DTLS"
[RFC8310], depending on their usage profile.
'''

[[spec]]
level = "SHOULD"
quote = '''
DNS clients SHOULD remember server IP addresses that don't support
DoQ.
'''

[[spec]]
level = "SHOULD"
quote = '''
Clients SHOULD NOT
attempt DoQ queries to a server that does not support DoQ for a
reasonable period (such as one hour per server).
'''

[[spec]]
level = "MAY"
quote = '''
DNS clients
following an out-of-band key-pinned usage profile [RFC7858] MAY be
more aggressive about retrying after DoQ connection failures.
'''

