// This file is @generated by prost-build from proto/dnstap.proto.
// Do not edit manually.
//
// To regenerate, run:
//   cargo test --features dnstap generate_dnstap_proto -- --ignored

// This file is @generated by prost-build.
/// "Dnstap": this is the top-level dnstap type, which is a "union" type that
/// contains other kinds of dnstap payloads, although currently only one type
/// of dnstap payload is defined.
/// See: <https://developers.google.com/protocol-buffers/docs/techniques#union>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Dnstap {
    /// DNS server identity.
    /// If enabled, this is the identity string of the DNS server which generated
    /// this message. Typically this would be the same string as returned by an
    /// "NSID" (RFC 5001) query.
    #[prost(bytes = "vec", optional, tag = "1")]
    pub identity: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// DNS server version.
    /// If enabled, this is the version string of the DNS server which generated
    /// this message. Typically this would be the same string as returned by a
    /// "version.bind" query.
    #[prost(bytes = "vec", optional, tag = "2")]
    pub version: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// Extra data for this payload.
    /// This field can be used for adding an arbitrary byte-string annotation to
    /// the payload. No encoding or interpretation is applied or enforced.
    #[prost(bytes = "vec", optional, tag = "3")]
    pub extra: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(enumeration = "dnstap::Type", required, tag = "15")]
    pub r#type: i32,
    /// One of the following will be filled in.
    #[prost(message, optional, tag = "14")]
    pub message: ::core::option::Option<Message>,
}
/// Nested message and enum types in `Dnstap`.
pub mod dnstap {
    /// Identifies which field below is filled in.
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Type {
        Message = 1,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Message => "MESSAGE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "MESSAGE" => Some(Self::Message),
                _ => None,
            }
        }
    }
}
/// Policy: information about any name server operator policy
/// applied to the processing of a DNS message.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Policy {
    /// type: the type of policy applied, e.g. "RPZ" for a
    /// policy from a Response Policy Zone.
    #[prost(string, optional, tag = "1")]
    pub r#type: ::core::option::Option<::prost::alloc::string::String>,
    /// rule: the rule matched by the message.
    ///
    /// In a RPZ context, this is the owner name of the rule in
    /// the Reponse Policy Zone in wire format.
    #[prost(bytes = "vec", optional, tag = "2")]
    pub rule: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// action: the policy action taken in response to the
    /// rule match.
    #[prost(enumeration = "policy::Action", optional, tag = "3")]
    pub action: ::core::option::Option<i32>,
    /// match: the feature of the message exchange which matched the rule.
    #[prost(enumeration = "policy::Match", optional, tag = "4")]
    pub r#match: ::core::option::Option<i32>,
    /// The matched value. Format depends on the matched feature .
    #[prost(bytes = "vec", optional, tag = "5")]
    pub value: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
/// Nested message and enum types in `Policy`.
pub mod policy {
    /// Match: what aspect of the message or message exchange
    /// triggered the application of the Policy.
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Match {
        /// Name in question section of query
        Qname = 1,
        /// Client IP address
        ClientIp = 2,
        /// Address in A/AAAA RRSet
        ResponseIp = 3,
        /// Authoritative name server, by name
        NsName = 4,
        /// Authoritative name server, by IP address
        NsIp = 5,
    }
    impl Match {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Qname => "QNAME",
                Self::ClientIp => "CLIENT_IP",
                Self::ResponseIp => "RESPONSE_IP",
                Self::NsName => "NS_NAME",
                Self::NsIp => "NS_IP",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "QNAME" => Some(Self::Qname),
                "CLIENT_IP" => Some(Self::ClientIp),
                "RESPONSE_IP" => Some(Self::ResponseIp),
                "NS_NAME" => Some(Self::NsName),
                "NS_IP" => Some(Self::NsIp),
                _ => None,
            }
        }
    }
    /// The Action taken to implement the Policy.
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Action {
        /// Respond with NXDOMAIN
        Nxdomain = 1,
        /// Respond with empty answer section
        Nodata = 2,
        /// Do not alter the response (passthrough)
        Pass = 3,
        /// Do not respond.
        Drop = 4,
        /// Truncate UDP response, forcing TCP retry
        Truncate = 5,
        /// Respond with local data from policy
        LocalData = 6,
    }
    impl Action {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Nxdomain => "NXDOMAIN",
                Self::Nodata => "NODATA",
                Self::Pass => "PASS",
                Self::Drop => "DROP",
                Self::Truncate => "TRUNCATE",
                Self::LocalData => "LOCAL_DATA",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NXDOMAIN" => Some(Self::Nxdomain),
                "NODATA" => Some(Self::Nodata),
                "PASS" => Some(Self::Pass),
                "DROP" => Some(Self::Drop),
                "TRUNCATE" => Some(Self::Truncate),
                "LOCAL_DATA" => Some(Self::LocalData),
                _ => None,
            }
        }
    }
}
/// Message: a wire-format (RFC 1035 section 4) DNS message and associated
/// metadata. Applications generating "Message" payloads should follow
/// certain requirements based on the MessageType, see below.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Message {
    /// One of the Type values described above.
    #[prost(enumeration = "message::Type", required, tag = "1")]
    pub r#type: i32,
    /// One of the SocketFamily values described above.
    #[prost(enumeration = "SocketFamily", optional, tag = "2")]
    pub socket_family: ::core::option::Option<i32>,
    /// One of the SocketProtocol values described above.
    #[prost(enumeration = "SocketProtocol", optional, tag = "3")]
    pub socket_protocol: ::core::option::Option<i32>,
    /// The network address of the message initiator.
    /// For SocketFamily INET, this field is 4 octets (IPv4 address).
    /// For SocketFamily INET6, this field is 16 octets (IPv6 address).
    #[prost(bytes = "vec", optional, tag = "4")]
    pub query_address: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// The network address of the message responder.
    /// For SocketFamily INET, this field is 4 octets (IPv4 address).
    /// For SocketFamily INET6, this field is 16 octets (IPv6 address).
    #[prost(bytes = "vec", optional, tag = "5")]
    pub response_address: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// The transport port of the message initiator.
    /// This is a 16-bit UDP or TCP port number, depending on SocketProtocol.
    #[prost(uint32, optional, tag = "6")]
    pub query_port: ::core::option::Option<u32>,
    /// The transport port of the message responder.
    /// This is a 16-bit UDP or TCP port number, depending on SocketProtocol.
    #[prost(uint32, optional, tag = "7")]
    pub response_port: ::core::option::Option<u32>,
    /// The time at which the DNS query message was sent or received, depending
    /// on whether this is an AUTH_QUERY, RESOLVER_QUERY, or CLIENT_QUERY.
    /// This is the number of seconds since the UNIX epoch.
    #[prost(uint64, optional, tag = "8")]
    pub query_time_sec: ::core::option::Option<u64>,
    /// The time at which the DNS query message was sent or received.
    /// This is the seconds fraction, expressed as a count of nanoseconds.
    #[prost(fixed32, optional, tag = "9")]
    pub query_time_nsec: ::core::option::Option<u32>,
    /// The initiator's original wire-format DNS query message, verbatim.
    #[prost(bytes = "vec", optional, tag = "10")]
    pub query_message: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// The "zone" or "bailiwick" pertaining to the DNS query message.
    /// This is a wire-format DNS domain name.
    #[prost(bytes = "vec", optional, tag = "11")]
    pub query_zone: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// The time at which the DNS response message was sent or received,
    /// depending on whether this is an AUTH_RESPONSE, RESOLVER_RESPONSE, or
    /// CLIENT_RESPONSE.
    /// This is the number of seconds since the UNIX epoch.
    #[prost(uint64, optional, tag = "12")]
    pub response_time_sec: ::core::option::Option<u64>,
    /// The time at which the DNS response message was sent or received.
    /// This is the seconds fraction, expressed as a count of nanoseconds.
    #[prost(fixed32, optional, tag = "13")]
    pub response_time_nsec: ::core::option::Option<u32>,
    /// The responder's original wire-format DNS response message, verbatim.
    #[prost(bytes = "vec", optional, tag = "14")]
    pub response_message: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// Operator policy applied to the processing of this message, if any.
    #[prost(message, optional, tag = "15")]
    pub policy: ::core::option::Option<Policy>,
    /// One of the HttpProtocol values described above. This field should only be
    /// set if socket_protocol is set to DOH.
    #[prost(enumeration = "HttpProtocol", optional, tag = "16")]
    pub http_protocol: ::core::option::Option<i32>,
}
/// Nested message and enum types in `Message`.
pub mod message {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Type {
        /// AUTH_QUERY is a DNS query message received from a resolver by an
        /// authoritative name server, from the perspective of the authoritative
        /// name server.
        AuthQuery = 1,
        /// AUTH_RESPONSE is a DNS response message sent from an authoritative
        /// name server to a resolver, from the perspective of the authoritative
        /// name server.
        AuthResponse = 2,
        /// RESOLVER_QUERY is a DNS query message sent from a resolver to an
        /// authoritative name server, from the perspective of the resolver.
        /// Resolvers typically clear the RD (recursion desired) bit when
        /// sending queries.
        ResolverQuery = 3,
        /// RESOLVER_RESPONSE is a DNS response message received from an
        /// authoritative name server by a resolver, from the perspective of
        /// the resolver.
        ResolverResponse = 4,
        /// CLIENT_QUERY is a DNS query message sent from a client to a DNS
        /// server which is expected to perform further recursion, from the
        /// perspective of the DNS server. The client may be a stub resolver or
        /// forwarder or some other type of software which typically sets the RD
        /// (recursion desired) bit when querying the DNS server. The DNS server
        /// may be a simple forwarding proxy or it may be a full recursive
        /// resolver.
        ClientQuery = 5,
        /// CLIENT_RESPONSE is a DNS response message sent from a DNS server to
        /// a client, from the perspective of the DNS server. The DNS server
        /// typically sets the RA (recursion available) bit when responding.
        ClientResponse = 6,
        /// FORWARDER_QUERY is a DNS query message sent from a downstream DNS
        /// server to an upstream DNS server which is expected to perform
        /// further recursion, from the perspective of the downstream DNS
        /// server.
        ForwarderQuery = 7,
        /// FORWARDER_RESPONSE is a DNS response message sent from an upstream
        /// DNS server performing recursion to a downstream DNS server, from the
        /// perspective of the downstream DNS server.
        ForwarderResponse = 8,
        /// STUB_QUERY is a DNS query message sent from a stub resolver to a DNS
        /// server, from the perspective of the stub resolver.
        StubQuery = 9,
        /// STUB_RESPONSE is a DNS response message sent from a DNS server to a
        /// stub resolver, from the perspective of the stub resolver.
        StubResponse = 10,
        /// TOOL_QUERY is a DNS query message sent from a DNS software tool to a
        /// DNS server, from the perspective of the tool.
        ToolQuery = 11,
        /// TOOL_RESPONSE is a DNS response message received by a DNS software
        /// tool from a DNS server, from the perspective of the tool.
        ToolResponse = 12,
        /// UPDATE_QUERY is a Dynamic DNS Update request (RFC 2136) received
        /// by an authoritative name server, from the perspective of the
        /// authoritative name server.
        UpdateQuery = 13,
        /// UPDATE_RESPONSE is a Dynamic DNS Update response (RFC 2136) sent
        /// from an authoritative name server, from the perspective of the
        /// authoritative name server.
        UpdateResponse = 14,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::AuthQuery => "AUTH_QUERY",
                Self::AuthResponse => "AUTH_RESPONSE",
                Self::ResolverQuery => "RESOLVER_QUERY",
                Self::ResolverResponse => "RESOLVER_RESPONSE",
                Self::ClientQuery => "CLIENT_QUERY",
                Self::ClientResponse => "CLIENT_RESPONSE",
                Self::ForwarderQuery => "FORWARDER_QUERY",
                Self::ForwarderResponse => "FORWARDER_RESPONSE",
                Self::StubQuery => "STUB_QUERY",
                Self::StubResponse => "STUB_RESPONSE",
                Self::ToolQuery => "TOOL_QUERY",
                Self::ToolResponse => "TOOL_RESPONSE",
                Self::UpdateQuery => "UPDATE_QUERY",
                Self::UpdateResponse => "UPDATE_RESPONSE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "AUTH_QUERY" => Some(Self::AuthQuery),
                "AUTH_RESPONSE" => Some(Self::AuthResponse),
                "RESOLVER_QUERY" => Some(Self::ResolverQuery),
                "RESOLVER_RESPONSE" => Some(Self::ResolverResponse),
                "CLIENT_QUERY" => Some(Self::ClientQuery),
                "CLIENT_RESPONSE" => Some(Self::ClientResponse),
                "FORWARDER_QUERY" => Some(Self::ForwarderQuery),
                "FORWARDER_RESPONSE" => Some(Self::ForwarderResponse),
                "STUB_QUERY" => Some(Self::StubQuery),
                "STUB_RESPONSE" => Some(Self::StubResponse),
                "TOOL_QUERY" => Some(Self::ToolQuery),
                "TOOL_RESPONSE" => Some(Self::ToolResponse),
                "UPDATE_QUERY" => Some(Self::UpdateQuery),
                "UPDATE_RESPONSE" => Some(Self::UpdateResponse),
                _ => None,
            }
        }
    }
}
/// SocketFamily: the network protocol family of a socket. This specifies how
/// to interpret "network address" fields.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SocketFamily {
    /// IPv4 (RFC 791)
    Inet = 1,
    /// IPv6 (RFC 2460)
    Inet6 = 2,
}
impl SocketFamily {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Inet => "INET",
            Self::Inet6 => "INET6",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INET" => Some(Self::Inet),
            "INET6" => Some(Self::Inet6),
            _ => None,
        }
    }
}
/// SocketProtocol: the protocol used to transport a DNS message.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SocketProtocol {
    /// DNS over UDP transport (RFC 1035 section 4.2.1)
    Udp = 1,
    /// DNS over TCP transport (RFC 1035 section 4.2.2)
    Tcp = 2,
    /// DNS over TLS (RFC 7858)
    Dot = 3,
    /// DNS over HTTPS (RFC 8484)
    Doh = 4,
    /// DNSCrypt over UDP (<https://dnscrypt.info/protocol>)
    DnsCryptUdp = 5,
    /// DNSCrypt over TCP (<https://dnscrypt.info/protocol>)
    DnsCryptTcp = 6,
    /// DNS over QUIC (RFC 9250)
    Doq = 7,
}
impl SocketProtocol {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Udp => "UDP",
            Self::Tcp => "TCP",
            Self::Dot => "DOT",
            Self::Doh => "DOH",
            Self::DnsCryptUdp => "DNSCryptUDP",
            Self::DnsCryptTcp => "DNSCryptTCP",
            Self::Doq => "DOQ",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UDP" => Some(Self::Udp),
            "TCP" => Some(Self::Tcp),
            "DOT" => Some(Self::Dot),
            "DOH" => Some(Self::Doh),
            "DNSCryptUDP" => Some(Self::DnsCryptUdp),
            "DNSCryptTCP" => Some(Self::DnsCryptTcp),
            "DOQ" => Some(Self::Doq),
            _ => None,
        }
    }
}
/// HttpProtocol: the HTTP protocol version used to transport a DNS message over
/// an HTTP-based protocol such as DNS over HTTPS.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum HttpProtocol {
    /// HTTP/1
    Http1 = 1,
    /// HTTP/2
    Http2 = 2,
    /// HTTP/3
    Http3 = 3,
}
impl HttpProtocol {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Http1 => "HTTP1",
            Self::Http2 => "HTTP2",
            Self::Http3 => "HTTP3",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "HTTP1" => Some(Self::Http1),
            "HTTP2" => Some(Self::Http2),
            "HTTP3" => Some(Self::Http3),
            _ => None,
        }
    }
}
