target = "https://www.rfc-editor.org/rfc/rfc9018#section-4.2"

# The Reserved Sub-Field
#
#    The value of the Reserved Sub-Field is reserved for future versions
#    of server-side cookie construction.  On construction, it MUST be set
#    to zero octets.  On Server Cookie verification, the server MUST NOT
#    enforce those fields to be zero, and the Hash should be computed with
#    the received value as described in Section 4.4.

[[spec]]
level = "MUST"
quote = '''
On construction, it MUST be set
to zero octets.
'''

[[spec]]
level = "MUST"
quote = '''
On Server Cookie verification, the server MUST NOT
enforce those fields to be zero, and the Hash should be computed with
the received value as described in Section 4.4.
'''

