target = "https://www.rfc-editor.org/rfc/rfc5155#section-8.4"

# Validating Name Error Responses
#
#    A validator MUST verify that there is a closest encloser proof for
#    QNAME present in the response and that there is an NSEC3 RR that
#    covers the wildcard at the closest encloser (i.e., the name formed by
#    prepending the asterisk label to the closest encloser).

[[spec]]
level = "MUST"
quote = '''
A validator MUST verify that there is a closest encloser proof for
QNAME present in the response and that there is an NSEC3 RR that
covers the wildcard at the closest encloser (i.e., the name formed by
prepending the asterisk label to the closest encloser).
'''

