//! Regenerate the DNSTAP protobuf Rust code from `proto/dnstap.proto`.
//!
//! Run with:
//!   cargo test -p hickory-dnstap generate_dnstap_proto -- --ignored
//!
//! This uses `protox` (pure-Rust protobuf compiler) and `prost-build` to
//! generate the code, so no external `protoc` binary is needed.

#[test]
#[ignore]
fn generate_dnstap_proto() {
    let proto_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/proto");
    let out_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/src");

    let file_descriptor_set =
        protox::compile(["dnstap.proto"], [proto_dir]).expect("Failed to compile proto files");

    let mut config = prost_build::Config::new();
    config.btree_map(["."]);
    config.out_dir(out_dir);

    config
        .compile_fds(file_descriptor_set)
        .expect("Failed to generate Rust code from proto");

    // prost-build names the output file after the protobuf package name
    let generated = std::path::PathBuf::from(out_dir).join("dnstap.rs");
    let target = std::path::PathBuf::from(out_dir).join("proto.rs");

    let content = std::fs::read_to_string(&generated).expect("Failed to read generated file");

    // Prepend a header comment, then write to proto.rs
    let with_header = format!(
        "// This file is @generated by prost-build from proto/dnstap.proto.\n\
         // Do not edit manually.\n\
         //\n\
         // To regenerate, run:\n\
         //   cargo test -p hickory-dnstap generate_dnstap_proto -- --ignored\n\
         \n{content}"
    );

    std::fs::write(&target, with_header).expect("Failed to write proto.rs");

    // Clean up the intermediate file
    let _ = std::fs::remove_file(&generated);

    println!("Generated {}", target.display());
}
