[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "conformance-tests"
publish = false
version = "0.1.0"

[dependencies]
base64 = "0.22"
dns-test.path = "../dns-test"

[lib]
doctest = false
