target = "https://www.rfc-editor.org/rfc/rfc8764#section-5.2.2"

# Setup Challenge
#
#    Upon receiving an LLQ Setup Request, a server implementing LLQs will
#    send a Setup Challenge to the requester (client).  An LLQ Setup
#    Challenge is a DNS response, with the DNS message ID matching that of
#    the Setup Request, and with all questions contained in the Setup
#    Request present in the Question section of the response.
#    Additionally, the challenge contains a single OPT pseudo-RR with an
#    LLQ OPTION for each LLQ request, indicating the success or failure of
#    each request.  The LLQ OPTIONS MUST be in the same order as the
#    questions they correspond to.  Note that in a Setup Request
#    containing multiple questions, some LLQs may succeed while others may
#    fail.
# 
#      +---------------+------------+---------------------------------+
#      | Field Name    | Field Type | Description                     |
#      +===============+============+=================================+
#      | OPTION-CODE   | u_int16_t  | LLQ (1)                         |
#      +---------------+------------+---------------------------------+
#      | OPTION-LENGTH | u_int16_t  | Length of following fields (18) |
#      +---------------+------------+---------------------------------+
#      | LLQ-VERSION   | u_int16_t  | Version of LLQ protocol         |
#      |               |            | implemented in server (1)       |
#      +---------------+------------+---------------------------------+
#      | LLQ-OPCODE    | u_int16_t  | LLQ-SETUP (1)                   |
#      +---------------+------------+---------------------------------+
#      | LLQ-ERROR     | u_int16_t  | [As Appropriate]                |
#      +---------------+------------+---------------------------------+
#      | LLQ-ID        | u_int64_t  | [As Appropriate]                |
#      +---------------+------------+---------------------------------+
#      | LLQ-LEASE     | u_int32_t  | [As Appropriate]                |
#      +---------------+------------+---------------------------------+
# 
#                 Table 5: Setup Challenge LLQ OPTION Format
# 
#    The Setup Challenge LLQ OPTION MUST be repeated once for each query
#    in the Questions section of the Setup Challenge.  Further details for
#    LLQ-ERROR, LLQ-ID and LLQ-LEASE are given below.
# 
#    LLQ-ERROR:
# 
#       NO-ERROR:         The LLQ Setup Request was successful.
# 
#       FORMAT-ERR:       The LLQ was improperly formatted.  Note that if
#                         the rest of the DNS message is properly
#                         formatted, the DNS header error code MUST NOT
#                         include a format error code, since to do so
#                         would cause ambiguity between the case where a
#                         client sends a valid LLQ Setup Request to a
#                         server that does not understand LLQ and the case
#                         where a client sends a malformed LLQ Setup
#                         Request to a server that does understand LLQ.
# 
#       SERV-FULL:        The server cannot grant the LLQ request because
#                         it is overloaded or the request exceeds the
#                         server's rate limit (see Section 8, Security
#                         Considerations).  Upon returning this error, the
#                         server MUST include in the LLQ-LEASE field a
#                         time interval, in seconds, after which the
#                         client may retry the LLQ Setup.
# 
#       STATIC:           The data for this name and type is not expected
#                         to change frequently, and the server, therefore,
#                         does not support the requested LLQ.  The client
#                         MUST honor the resource record TTLs returned and
#                         MUST NOT poll sooner than indicated by those
#                         TTLs, nor should it retry the LLQ Setup for this
#                         name and type.
# 
#       BAD-VERS:         The protocol version specified in the client's
#                         Setup Request is not supported by the server.
# 
#       UNKNOWN-ERR:      The LLQ was not granted for some other reason
#                         not covered by the preceding error code values.
# 
#    LLQ-ID:           On success, a random number generated by the server
#                      that is unique on the server for the requested
#                      name/type/class.  The LLQ-ID SHOULD be an
#                      unpredictable random number.  A possible method of
#                      allocating LLQ-IDs with minimal bookkeeping would
#                      be to store the time, in seconds since the Epoch,
#                      in the high 32 bits of the field, and a
#                      cryptographically generated 32-bit random integer
#                      in the low 32 bits.
# 
#                      On error, the LLQ-ID is set to 0.
# 
#    LLQ-LEASE:        On success, the actual life of the LLQ, in seconds.
#                      Value may be greater than, less than, or equal to
#                      the value requested by the client, as per the
#                      server administrator's policy.  The server MAY
#                      discard the LLQ after this LLQ-LEASE expires unless
#                      the LLQ has been renewed by the client (see
#                      Section 7, "LLQ Lease-Life Expiration").  The
#                      server MUST NOT generate events (see Section 6,
#                      "Event Responses") for expired LLQs.
# 
#                      On SERV-FULL error, LLQ-LEASE MUST be set to a time
#                      interval, in seconds, after which the client may
#                      retry the LLQ Setup.
# 
#                      On other errors, the LLQ-LEASE MUST be set to 0.

[[spec]]
level = "MUST"
quote = '''
The LLQ OPTIONS MUST be in the same order as the
questions they correspond to.
'''

[[spec]]
level = "MUST"
quote = '''
The Setup Challenge LLQ OPTION MUST be repeated once for each query
in the Questions section of the Setup Challenge.
'''

[[spec]]
level = "MUST"
quote = '''
Note that if
the rest of the DNS message is properly
formatted, the DNS header error code MUST NOT
include a format error code, since to do so
would cause ambiguity between the case where a
client sends a valid LLQ Setup Request to a
server that does not understand LLQ and the case
where a client sends a malformed LLQ Setup
Request to a server that does understand LLQ.
'''

[[spec]]
level = "MUST"
quote = '''
Upon returning this error, the
server MUST include in the LLQ-LEASE field a
time interval, in seconds, after which the
client may retry the LLQ Setup.
'''

[[spec]]
level = "MUST"
quote = '''
The client
MUST honor the resource record TTLs returned and
MUST NOT poll sooner than indicated by those
TTLs, nor should it retry the LLQ Setup for this
name and type.
'''

[[spec]]
level = "SHOULD"
quote = '''
The LLQ-ID SHOULD be an
unpredictable random number.
'''

[[spec]]
level = "MAY"
quote = '''
The server MAY
discard the LLQ after this LLQ-LEASE expires unless
the LLQ has been renewed by the client (see
Section 7, "LLQ Lease-Life Expiration").
'''

[[spec]]
level = "MUST"
quote = '''
The
server MUST NOT generate events (see Section 6,
"Event Responses") for expired LLQs.
'''

[[spec]]
level = "MUST"
quote = '''
On SERV-FULL error, LLQ-LEASE MUST be set to a time
interval, in seconds, after which the client may
retry the LLQ Setup.
'''

[[spec]]
level = "MUST"
quote = '''
On other errors, the LLQ-LEASE MUST be set to 0.
'''

