target = "https://www.rfc-editor.org/rfc/rfc9471#section-3.2"

# Glue for Sibling Domain Name Servers
#
#    This document clarifies that when a name server generates a referral
#    response, it SHOULD include all available glue records in the
#    additional section.  If, after adding glue for all in-domain name
#    servers, the glue for all sibling domain name servers does not fit
#    due to message size constraints, the name server MAY set TC=1 but is
#    not obligated to do so.
# 
#    Note that users may experience resolution failures for domains with
#    cyclically dependent sibling name servers when the delegating name
#    server chooses to omit the corresponding glue in a referral response.
#    As described in Section 2.3, such domains are rare.

[[spec]]
level = "SHOULD"
quote = '''
This document clarifies that when a name server generates a referral
response, it SHOULD include all available glue records in the
additional section.
'''

[[spec]]
level = "MAY"
quote = '''
If, after adding glue for all in-domain name
servers, the glue for all sibling domain name servers does not fit
due to message size constraints, the name server MAY set TC=1 but is
not obligated to do so.
'''

